name: dt-weather-app
memory: 512Mi
cpu: 1
max-instances: 10
min-instances: 0
timeout: 300

owner: anjola.sigbeku@datatorque.com
team: engineering
path-pattern: /weather/*
priority: 300

env-vars:
  - name: LOG_LEVEL
    value: info
